export const User = {
    SET_USER: 'SET_USER',
    FOLLOW_USER: 'FOLLOW_USER',
    SET_PROFILE: 'SET_PROFILE'
}

export const Post = {
    LOAD_POSTS:  'LOAD_POSTS',
    VIEW_POST: 'VIEW_POST',
    LIKE_POST: 'LIKE_OR_UNLIKE_POST',
    ADD_COMMENT: 'ADD_COMMENT'
}

export const Common = {
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    CHANGE_RESEARCH: 'CHANGE_RESEARCH'
}

export const Inscription = {
    TOGGLE_INSTRUCTION_BUTTON: 'TOGGLE_INSTRUCTION_BUTTON',
    TOGGLE_USERNAME_VALID: 'TOGGLE_USERNAME_VALID',
    TOGGLE_USERNAME_PROCESSING: 'TOGGLE_USERNAME_PROCESSING'
}