export {default as InputDateDeNaissance} from './Inputs/DateDeNaissance'
export {default as InputUsername} from './Inputs/Username'
export {default as InputNames} from './Inputs/Names'
export {default as InputPasswords} from './Inputs/Passwords'
export {default as InputEmail} from './Inputs/Email'
export {default as InputSexe} from './Inputs/Sexe'
