export const User = {
    FOLLOW_USER: 'FOLLOW_USER',
    SET_USER:'SET_USER',
    ERROR: 'ERROR',
    SET_PROFILE: "SET_PROFILE"
}

export const Post = {
    LOAD_POSTS:  'LOAD_POSTS',
    VIEW_POST: 'VIEW_POST',
    LIKE_POST: 'LIKE_OR_UNLIKE_POST',
    ADD_COMMENT: 'ADD_COMMENT'
}
