export const User = {
    FOLLOW_USER: 'FOLLOW_USER',
    SET_PROFILE: 'SET_PROFILE'
}

export const Post = {
    LOAD_POSTS:  'LOAD_POSTS',
    VIEW_POST: 'VIEW_POST',
    LIKE_POST: 'LIKE_OR_UNLIKE_POST',
    ADD_COMMENT: 'ADD_COMMENT'
}

export const Common = {
    TOGGLE_MODAL: 'TOGGLE_MODAL'
}

export const Inscription = {
    SET_USER: 'SET_USER',
    TOGGLE_INSCRIPTION_BUTTON: 'TOGGLE_INSCRIPTION_BUTTON',
    TOGGLE_USERNAME_VALID: 'TOGGLE_USERNAME_VALID',
    TOGGLE_USERNAME_PROCESSING: 'TOGGLE_USERNAME_PROCESSING',
    CHANGE_INSCRIPTION_DATA: 'CHANGE_INSCRIPTION_DATA',
    DELETE_INSCRIPTION_DATA: "DELETE_INSCRIPTION_DATA"
}

export const Header = {
    CHANGE_RESEARCH: 'CHANGE_RESEARCH',
    SEARCHING: 'SEARCHING'
}